export const Endpoint = {
  SIGNIN: "/auth/login",
  SIGNUP: "/auth/register",
  VERIFY: "/auth/code",
  JOIN_WORKSPACE: "/users/join",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/set-password",
  CHANGE_PASSWORD: "/auth/update-pasword",
  REFRESH_TOKEN: "auth/refresh-token",
  USERS: "/users",
  USERS_APPROVE: "/users/approve?company={company}",
  USERS_REJECT: "/users/reject?company={company}",
  USER_ITEM: "/users/{id}",
  USERS_INACTIVE: "/users/inactive",
  PROFILE: "/users/me",
  INVITE_USER_TO_COMPANY: "/users/inviteUserToCompany",
  COMPANIES: "/companies",
  COMPANY_ADD_MEMBER: "/companies/add-member",
  COMPANY_MEMBERS: "/users/members",
  COMPANIES_APPROVE: "/companies/approve",
  COMPANIES_REJECT: "/companies/reject",
  MY_COMPANY: "/companies/me",
  COMPANY_ITEM: "/companies/{id}",
  PROJECTS: "/projects",
  PROJECT_GENERATE: "/project/project-generate/",
  PROJECT_ITEM: "/projects/{id}",
  PROJECT_FILE: "/projects/{id}/files",
  PROJECT_MEMBERS: "/projects/{id}/members",
  PROJECT_TASKS: "/tasks",
  PROJECT_ACTIVITIES: "/activities",
  PROJECT_TASK_ITEM: "/tasks/{id}",
  CURRENCY: "projects/currency",
  TASKS: "/tasks/add",
  TASK_GENERATE: "task/task-generate/",
  TASK_LIST: "/tasks/task-list/{id}",
  SUB_TASKS: "/tasks/sub",
  SUB_TASK: "/tasks/sub-task",
  TASK_ITEM: "/tasks/task",
  TASKS_INACTIVE: "/tasks/task-inactive",
  SUB_TASKS_INACTIVE: "/tasks/sub-inactive",
  TASK_LIST_INACTIVE: "/tasks/task-list",
  CHANGE_PARENT_TASK: "/tasks/change-parent-task",
  TODO_DONE: "/tasks/isdone",
  CONVERT_TASK: "/tasks/convert-task",
  CONVERT_SUB_TASK: "/tasks/convert-subtask",
  CONVERT_SUB_TASK_TO_TASK: "/tasks/convert-task-by-subtask",
  DELETE_DEPENDENCY: "/tasks/delete-dependences",
  ORDER_TASK: "/tasks/update-priority-todo-task",
  ORDER_SUB_TASK: "/tasks/update-priority-todo-sub",
  DELETE_TO_DO: "/tasks/delete-todo-list",
  TASK_MOVE: "/tasks/move",
  TASK_COMMENT: "/tasks/comment",
  SUB_TASK_COMMENT: "/tasks/comment-sub",
  PROJECT_TYPES_ALL: "type-project/all",
  PROJECT_TYPES: "type-project",
  PROJECT_TYPE_ITEM: "type-project/{id}",
  PROJECT_TYPES_INACTIVE: "type-project/inactive",
  SALES_LIST: "/sales/all",
  CREATE_DEAL: "/sales",
  SALES_DEAL_EXPORT: "/sales/export/deal",
  SALES_DEAL_DETAIL: "/sales/{id}",
  SALES_TODO: "/sales/todo",
  SALES_TODO_DETAIL: "/sales/todo/{id}",
  SALES_SERVICE: "/sales/service/",
  SALES_SERVICE_DETAIL: "/sales/service/{id}",
  SALES_SECTION_DETAIL: "/sales/section/{id}",
  SALES_COMMENT: "/sales/comment",
  TAGS: "/tags",
  TAGS_ALL: "/tags/all",
  TAGS_DETAIL: "/tags/{id}",
  CLIENT_COMPANIES: "/clients",
  CLIENT_COMPANIES_MULTI: "/clients/multi-id",
  CLIENT_COMPANIES_DETAIL: "/clients/detail",
  CLIENT_COMPANIES_ADD_MEMBER: "/clients/add-member",
  CLIENT_COMPANIES_EMPLOYEES: "/clients/employees",

  COST_RATE: "/cost-rate/{employeeId}",
  COST_RATE_DETAIL: "/cost-rate/{employeeId}/{id}",
  COST_RATE_DELETE_MULTI: "/cost-rate/delete-multi-cost-rate/{employeeId}",
  COST_RATE_CHART: "/cost-rate/chart/{employeeId}",

  COST_HISTORY: "/cost-history",

  HOLIDAY_CALENDAR: "/cost-rate/holiday-calendar",
  HOLIDAY_CALENDAR_DETAIL: "/cost-rate/holiday-calendar/{id}",
  HOLIDAY_LIST: "/cost-rate/holiday-list",
  HOLIDAY_LIST_DETAIL: "/cost-rate/holiday-list/{id}",

  BUDGET_ALL: "/budgets/all",
  BUDGET_CREATE: "/budgets",
  BUDGET_UPDATE: "/budgets/{budgetId}",
  BUDGET_DELETE_BY_ID: "/budgets/{budgetId}",
  BUDGET_GET_BY_ID: "/budgets/budget-by-id/{id}",
  BUDGET_GET_FEED: "/budgets/feed/{id}",
  BUDGET_GET_TIME_RANGES: "/budgets/times/{id}",
  BUDGET_TIME_RANGES: "/budgets/times",
  BUDGET_DELETE_TIME_RANGES: "/budgets/times/{id}",
  BUDGET_SERVICE_LIST: "/budgets/service/{id}",
  BUDGET_SERVICE_ADD: "/budgets/service",
  BUDGET_SERVICE_UPDATE: "/budgets/service/{id}",
  BUDGET_SECTION_DELETE: "/budgets/section/{id}",
  BUDGET_TIME_RANGES_BY_ID: "/budgets/time/{timeId}",
  BUDGET_TIME_RANGES_UPDATE: "/budgets/time/{id}",
  BUDGET_TIME_RANGES_DELETE: "/budgets/time/{id}",
  BUDGET_EXPENSE_CREATE: "/budgets/expense/create-expense",
  BUDGET_EXPENSE_LIST: "/budgets/expense/get-all-expense/{budgetId}",
  BUDGET_EXPENSE_DETAIL: "/budgets/expense/get-detail-expense/{expenseId}",
  BUDGET_EXPENSE_DETAIL_EXPORT:
    "/budgets/expense/export-all-expense/{expenseId}",
  BUDGET_EXPENSE_DETAIL_UPDATE: "/budgets/expense/update-expense/{expenseId}",
  BUDGET_EXPENSE_DETAIL_DELETE: "/budgets/expense/delete-expense/{expenseId}",
  BUDGET_RECURRING_ADD: "budgets/recurring/create-recurring",

  POSITIONS_ALL: "/positions/all",
  POSITIONS: "/positions",
  POSITION_ITEM: "/positions/{id}",
  POSITIONS_INACTIVE: "/positions/inactive",

  UPLOAD: "/files/upload-avatar",
  SIGNUP_UPLOAD: "/avatar/upload",
  UPLOAD_LINK: "/files/upload-link",
  DOWNLOAD_LINK: "/in/files/download-links",

  RESOURCE_PLANNING: "/resources",
  RESOURCE_PLANNING_LIST: "/resources/all",
  RESOURCE_PLANNING_DETAIL: "/resources/{id}",
  MY_RESOURCE_PLANNING: "/resources/me",

  MY_TIME_SHEET: "/timesheets/me",
  WORK_LOG: "/timesheets/log",
  COMPANY_TIME_SHEET: "timesheets/company",
  TIME_SHEET: "/timesheets",
  PIN: "/timesheets/pin",
  SAME_WORKER: "timesheets/same-worker",

  // Docs
  DOCS: "/docs",
  CREATE_DOCS: "/docs",
  UPDATE_DOCS: "/docs/{id}",
  DETAIL_DOCS: "/docs/detail/",
  HISTORY_DOCS: "/docs/history/{id}",
  ADD_PERM_DOCS: "/docs/add-perm/",
  PERM_DOCS: "/docs/perm/",

  //feedback
  FEEDBACK: "/feedback",
  RESPONDFEEDBACK: "/feedback/{id}/response",

  // blog
  CATEGORY_BLOG: "/category",
  BLOGS: "/post",
  DETAIL_BLOG: "/post/{id}",
  GET_BLOG_COMMENT: "/post/{id}/comment",
  GET_BLOG_TAGS: "/post/tags",

  //carrer
  CAREER: "/job-post",
  UPADATECAREER: "/job-post/{id}",
  DETAIL_CAREER: "/job-post/{slug}",
  UPDATE_STATUS_CAREER: "/job-post/{id}/status/{status}",
  GET_APPLICANTS_CAREER: "/job-post/{slug}/applicants",
  RESPONDAPPLICANT: "/job-post/response-applicant",

  //Billing
  BILLING: "/billing",
  DETAIL_BILLING: "/bill/export/{id}",
  EXPORT_BILLING: "/billToExport",
  INTERACTION_BILLING: "/bill_interaction",
  INTERACTION_BILLING_BY_BILL: "/bill_interaction/{id}",
  ADD_USER_BILL: "/invoices/{id}/add-members",
  CHANGE_BILL: "/bill/{id}",
  PAYMENT_BILL: "/payment",
  CUSTOM_PAYMENT: "/payments/{id}",
  ALL_CUSTOM_PAYMENT: "/payments/all/{id}",
  TAG: "/tag",
  CUSTOM_TAG: "/tag/{id}",
  UPDATE_BILL_TAG: "/bill/updateTag/{id}",

  //Budget
  BUDGET: "/budgets/all",
  DETAIL_BUDGET: "/budgets/budget-by-id/{id}",
  CREATE_SERVICE_BUDGET: "/budgets/service",
  SERVICE_BY_BUDGET: "/budgets/service/{id}",

  //Content
  CONTENT_HOME_BANNER: "/content/home/banner",
  CONTENT_HOME_EXPLORE: "/content/home/explore-how-we",
  CONTENT_HOME_POWER: "/content/home/powerful-agent",

  CONTENT_ABOUT_US_BANNER: "/content/about-us/banners",
  CONTENT_ABOUT_US_QUESTIONS: "/content/about-us/questions",
  CONTENT_ABOUT_US_MISSIONS: "/content/about-us/missions",
  CONTENT_ABOUT_US_MOST_VIEW_ARTICLES: "/content/about-us/most-viewed-articles",
  CONTENT_ABOUT_US_ALL_START_TEAM: "/content/about-us/all-star-team",
  CONTENT_ABOUT_US_ONE_START_TEAM: "/content/about-us/all-star-team/{id}",

  CONTENT_HELP_CENTER_BANNER: "/content/help-center/banner",
  CONTENT_HELP_CENTER_USAGE_TIPS: "/content/help-center/usage-tips",

  CONTENT_TRUST_CENTER_BANNER: "/content/trust-center/banner",
  CONTENT_TRUST_CENTER_BUILDING_TRUST: "/content/trust-center/building-trust",

  CONTENT_AI_BANNER: "content/AI/banner",
  CONTENT_AI_BRANDS: "content/AI/brands",
  CONTENT_AI_PRODUCTIVITY: "content/AI/productivity",
  CONTENT_AI_PROMOTE: "content/AI/promote-your-operation",

  CONTENT_PRICING_BANNER: "content/pricing/banner",
  CONTENT_PRICING_BANNER2: "content/pricing/banner2",
  CONTENT_PRICING_UNLOCK: "content/pricing/unlock-unbeatable-value",
  CONTENT_PRICING_PARTNERS: "content/pricing/partners",

  //AI Chat
  AI_CHAT_EXAMPLE_PROMPT: "ai-chat/example-prompt",
  AI_CHAT_SESSION: "ai-chat/chat-sessions",
  AI_CHAT: "ai-chat/chat",
  AI_CHAT_PERSONA: "ai-chat/personas",
  AI_CHAT_TONE: "ai-chat/tones",
  AI_CHAT_DELETE_ALL_SESSION: "ai-chat/close-all-chat-session",

  //AI Agent
  AI_AGENT: "/agent",
  AI_AGENT_DELETE: "/agent/delete",
  AI_AGENT_CREATE: "/agent/create",
  AI_AGENT_PROMPT_TEMPLATE: "/agent/prompt-template",
  AI_AGENT_UPDATE: "/agent/update",
  AI_AGENT_ADD_SOURCE: "/agent/add-source-knowledge",
  AI_AGENT_GET_SOURCE: "/agent/:agentId/get-knowledge",
  AI_AGENT_RESYNCE_SOURCE: "/agent/:agentId/resync-knowledge",
  AI_AGENT_DELETE_SOURCE:
    "/agent/:agentID/delete-source-knowledge/:knowledgeId",
  AI_AGENT_CREATE_COMMAND: "/agent/create-command",
  AI_AGENT_GET_COMMAND: "/agent/:agentId/commands",
  AI_AGENT_CHAT: "/agent/chat",

  //Invoice
  INVOICE: "/invoices",
  DETAIL_INVOICE: "/invoices/{id}",

  // AI Assistants Docs
  AI_DOCS_SUMMARIZE: "/docs/summerization/document",
  AI_DOCS_COVERT_SHEET: "/docs/convert/sheet",
  AI_DOCS_IMPORT_MD: "/docs/import/md",
  AI_DOCS_IMPORT_OPML: "/docs/import/opml",
};
