enum TASK_ACTION {
  CREATE_TASK_LIST = "CREATE_TASK_LIST",
  MOVE_TASK = "MOVE_TASK",
  UPDATE_INACTIVE_TASK_LIST = "UPDATE_INACTIVE_TASK_LIST",
  UPDATE_TASK_LIST = "UPDATE_TASK_LIST",
  UPDATE_TASK = "UPDATE_TASK",
  UPDATE_SUB_TASK = "UPDATE_SUB_TASK",
  UPDATE_INACTIVE_TASK = "UPDATE_INACTIVE_TASK",
  UPDATE_INACTVE_SUB_TASK = "UPDATE_INACTVE_SUB_TASK",
  UPDATE_INACTIVE_SUB_TASK = "UPDATE_INACTIVE_SUB_TASK",
  CREATE_TASK = "CREATE_TASK",
  CREATE_SUB_TASK = "CREATE_SUB_TASK",
}

export default TASK_ACTION;
